###Array Basics

In [5]:
from array import array
import sys

In [4]:
arr1= array('i', [1,2,3,4])

In [13]:
print(arr1)
print(max(arr1))
print(min(arr1))
print(sum(arr1))

array('i', [1, 2, 3, 4])
4
1
10


###NUMPY

In [15]:
import numpy

In [21]:
arr2= numpy.array([1,2,3,4,5])

In [22]:
print(arr2)

[1 2 3 4 5]


In [25]:
print(type(arr2))
print(len(arr2))
print(arr2.shape)

<class 'numpy.ndarray'>
5
(5,)


In [28]:
arr3=numpy.array([[1,2,3],[4,5,6]])
print(arr3.shape)
print(len(arr3))

(2, 3)
2


In [1]:
numpy.concatenate(arr1, arr2)

NameError: name 'numpy' is not defined

In [7]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]]) 
print(np.concatenate(a,b))

TypeError: only integer scalar arrays can be converted to a scalar index

In [8]:
print np.concatenate((a,b))

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (3627984973.py, line 1)

In [12]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)

print ('Original array is:')
print (a)
print ('\n')

print ('Modified array is:')
for x in np.nditer(a):
   print (x)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


In [13]:
a = np.array([[3,7],[9,1]]) 
print(np.sort(a))

[[3 7]
 [1 9]]


In [14]:
print (np.sort(a, axis = 0))

[[3 1]
 [9 7]]


In [15]:
dt = np.dtype([('name', 'S10'),('age', int)]) 
a = np.array([("raju",21),("anil",25),("ravi", 17), ("amar",27)], dtype = dt)
print(np.sort(a, order="name"))


[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]


In [18]:
from numpy import random
print(random().randint(100))

TypeError: 'module' object is not callable